SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

DROP DATABASE IF EXISTS paymybuddyTest;

CREATE DATABASE paymybuddyTest;

USE paymybuddyTest;

DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
USERNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
CONNECTIONS INT NULL
);

LOCK TABLES USER WRITE;

INSERT INTO USER(ID,USERNAME,EMAIL,PASSWORD) VALUES
(1,'Jaques', 'jaques@gmail.com', '$2a$10$U4PLJ0QP2z8PdZPlSaehUekflF5hBoW5JMvVf685e4beG.NTWbNpq'),
(2,'Pierre', 'pierre@gmail.com', '$2a$10$.lx.1.Ol/HacxRsshsiHU.FOQF7D3lJmTKFTZTu2eklcn9lLsjfUa'),
(3,'Jean', 'jean@gmail.com', '$2a$10$A3.v9qG4LWhxtUwsb/3/KuPhgOUVAsvnbinMCqsQt4MBGQFvcRf3m'),
(4,'Michel', 'michel@gmail.com', '$2a$10$6oMht.JCoEeiWi385ZQlI.FbvxOtIFb0g03e5syVoR8GnwFCtPXLe');

UNLOCK TABLES;

DROP TABLES IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION (
ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
SENDER INT NULL,
RECEIVER INT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,
AMOUNT DOUBLE NOT NULL,
FOREIGN KEY(SENDER)
REFERENCES USER(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(RECEIVER)
REFERENCES USER(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

LOCK TABLES TRANSACTION WRITE;

INSERT INTO TRANSACTION(ID,SENDER, RECEIVER, DESCRIPTION, AMOUNT) VALUES
(1, 1, 2, 'restaurant', 25),
(2, 2, 1, 'magasin', 30),
(3, 3, 4, 'note de frais', 50),
(4, 4, 3, 'noel', 120);

UNLOCK TABLES;

DROP TABLES IF EXISTS USER_FRIENDS;

CREATE TABLE USER_FRIENDS (
ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
USER_ID INT NULL,
USER_FRIENDS INT NULL,
FOREIGN KEY(USER_ID)
REFERENCES USER(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

LOCK TABLES USER_FRIENDS WRITE;

INSERT INTO USER_FRIENDS(USER_ID, USER_FRIENDS) VALUES
(1,2),(1,3),(1,4),(2,1),(2,4),(3,1),(3,4),(4,1),(4,2),(4,3);

UNLOCK TABLES;

COMMIT;